name: Test pip installation

on: [push]

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install mpoints via pip
        run: |
          pip install mpoints
      - name: Test installation
        run: |
          python -c "import mpoints;"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: extract tests
        run: |
          echo $PWD
          cd ../..
          echo $PWD
          mkdir repo
          ls
          mv mpoints ./repo/
          ls
          cp -r repo/mpoints/tests ./
          ls
          ls tests
      - name: Test with pytest
        run: |
          echo $PWD
          pip install pytest
          pytest tests/*_test.py

